apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::851725359401:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-ST0Sw7YtPRjd
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::851725359401:user/Harish
      username: Harish
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-08T15:56:47Z"
  name: aws-auth
  namespace: kube-system
  uid: b6b4e0a9-133c-4da9-97c7-5c170efc1a5d
